default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development: &development
  <<: *default
  database: movies_unoptimized

test:
  <<: *default
  database: movie_time_test

production:
  <<: *development
